<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>

		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
		<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
		<meta content="black" name="apple-mobile-web-app-status-bar-style">

		<title>2014 挺好的！綠黨政治代理人</title>
		<meta name="keywords" content="綠黨,挺好的,九合一,選舉,greenparty" />
		<meta property="og:title" content="2014 挺好的！綠黨政治代理人" />
		<meta property="og:type" content="website"/>
		<meta property="og:url" content="http://green.democracy.tw/" />
		<meta property="og:image" content="http://green.democracy.tw/images/fbcover.jpg" />
		<meta property="og:site_name" content="2014 挺好的！綠黨政治代理人" /> 
		<meta property="og:description" content="2014 挺好的人選、挺好的政黨、挺好的！台灣綠黨政治代理人官方網站：新政治，從地方開始！今年綠黨的政治代理人分散在全台灣各地，包括台北市文祥里、淡水、三芝、石門、八里、土城、三峽、樹林、鶯歌、基隆七堵、桃園市、中壢、平鎮、新竹東區、竹東、高雄市三民區、澎湖馬公。我們要向住在這些地區的您，推薦我們最好的政治代理人！即使您不住在這些區域，我們也需要您大力的分享推薦給其他朋友！" />  
		<meta property="fb:app_id" content="687618544645054" />
		<meta property="fb:admins" content="100000125299492" />
		<meta property="og:locale" content="zh_TW" />
		<meta property="og:locale" content="zh_TW" />
		<meta property="og:see_also" content="http://greenparty.org.tw/">		
		<link rel="shortcut icon" href="/favicon.ico"/>
		<meta content="#191d24" name="msapplication-TileColor">
		<meta content="/images/fbcover_144.png" name="msapplication-TileImage">
		<link href="http://green.democracy.tw/images/fbcover_144.png" rel="apple-touch-icon-precomposed">

         <link rel="stylesheet" type="text/css" href="/css/normalize.min.css">
         <link rel="stylesheet" type="text/css" href="/css/main.css">
         <link rel="stylesheet" type="text/css" href="/css/responsive.css">
         <link rel="stylesheet" type="text/css" href="/css/flexslider.css">
         <link rel="stylesheet" type="text/css" href="/css/font-awesome.css">
         <link rel="stylesheet" type="text/css" href="/js/fancybox/jquery.fancybox.css?v=2.1.4" media="screen" />
         <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>         
<!--GA-->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54051080-1', 'auto');
  ga('send', 'pageview');		
  </script>		
<!--GA-->  
    </head>
    <body>
    	
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=687618544645054&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <!--[if lt IE 7]>
        <p class="chromeframe">你的瀏覽器太舊了，請升級或下載 <a href="http://www.google.com/chromeframe/?redirect=true"> Google Chrome Frame </a> 來瀏覽此網站</p>
    <![endif]-->
	


    <!-- Start Outter Wrapper / Feature Image -->	
    <div class="outter-wrapper feature">
		<div class="bannerShadowNone" style="background-image: url('/images/index_banner3.jpg');"></div>    	
    </div>
    
	<div id="sticky-anchor"></div>
    <!-- Start Outter Wrapper -->
    <div id="navall" class="outter-wrapper header-container">
    
    	<!-- Start Main Navigation -->
    	<div class="wrapper">
    	    <header class="clearfix">
    	    	
    	    	<a href="http://green.democracy.tw/" class="logo"><img src="/images/gp_badge.png?v2" alt="Logo" /> <span id="logo-word"></span></a>
    	        <span class="stickname" id="thisname"></span>
    	    	
    	        <nav id="nav-wrap">
    	        	<ul class="nav" id="nav">
    	        	    	
    	            	<li class="nav-parent last donate"><a href="http://www.greenparty.org.tw/civicrm/contribute/transact?reset=1&id=4"><em class="fa fa-heart"></em> 捐款支持</a>

    	            	</li>
    	                

    	        	    	                
    	            </ul>                	
    	        </nav>
    	    </header>
    	</div>
    	<!-- End Main Navigation -->
    </div>
    <!-- End Outter Wrapper -->
    <div id="space"></div>
    	
    <div class="outter-wrapper">	
    	 <!-- Start Main Body -->
        <div class="main-container">
            <div class="main wrapper clearfix">
            	<!-- Start Main Content -->				
            	
                <div class="main-content">


				<h1>關於綠黨</h1>
                	<p class="lead">國際上的綠黨於 70 年代興起，陸續在各國議會取得席次。1996 年台灣綠黨成立，與全球 91 個綠黨共同遵循全球綠人憲章的六大核心價值，以社運力量的參政平台出發投入各層級選舉。上屆選舉綠黨獲得近23萬政黨票，已成為台灣第五大黨。</p>
                	
                	
                	<div class="clearfix">	
						<img src="/images/dm.jpg" style="width:100%; max-width: 1753px;">
                	</div>

				<!-- add here-->
				</div>
				

        	</div> <!-- #main -->
        </div> <!-- #main-container -->
    </div>	


	<?php require_once 'api/footer.inc'; ?>
	
	<!-- Start Scripts -->
	<!--<script type="text/javascript" src="/js/vendor/jquery-1.8.3.min.js"></script>-->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		        				
	<script type="text/javascript" src="/js/fitvids.min.js"></script>
	<script type="text/javascript" src="/js/fancybox/jquery.fancybox.js?v=2.1.4"></script>
	<script type="text/javascript" src="/js/placeholder.js"></script>
	<script type="text/javascript" src="/js/jquery.flexslider-min.js"></script>
	<script type="text/javascript" src="/js/mosaic.1.0.1.min.js"></script>
	<script type="text/javascript" src="/js/cleantabs.jquery.js"></script>

	<script type="text/javascript" src="/js/contact.js"></script>
	<script type="text/javascript" src="/js/jquery.form.js"></script>
	<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
	<script type="text/javascript" src="/js/twphone.js"></script>

	<script type="text/javascript" src="/js/jquery.stellar.min.js"></script>
	<script type="text/javascript" src="/js/jquery.scrollUp.min.js"></script>
	<script type="text/javascript" src="/js/selectivizr-min.js"></script>
	
	<script type="text/javascript" src="/js/main.js"></script>
 
	</body>
</html>
