	<!-- /////////////////// --> 			
	<!-- Start Widget Footer -->
	<div class="outter-wrapper widget-footer main clearfix">
		<div class="wrapper clearfix">
			
			<!-- Start Column -->
			<div class="fourth widget">
				<a href="http://www.greenparty.org.tw"><h3>台灣綠黨</h3></a>
				<p>國際上的綠黨於 70 年代興起，陸續在各國議會取得席次。1996 年台灣綠黨成立，與<a href="http://www.globalgreens.org/parties" target="_blank">全球 91 個綠黨</a>共同遵循全球綠人憲章的<a href="http://hackfoldr.org/greenparty/http%253A%252F%252Fwww.greenparty.org.tw%252Fsites%252Fwww.greenparty.org.tw%252Ffiles%252Fglobal_greens_charter_2012_-_chinese__english.pdf" target="_blank">六大核心價值</a>，以社運力量的參政平台出發投入各層級選舉。上屆選舉綠黨獲得近23萬政黨票，已成為台灣第五大黨。</p><a href="http://green.democracy.tw" target="_self" ><div class="btn small-btn " style="background-color:#a8141a;">了解所有候選人</div></a>

			</div>


<?php


?>
			<!-- Start Column -->
			<div class="fourth widget footer-news">
				<h3>最新訊息</h3>
                			<div class="mosaic-block fade" style="max-height:120px; background-img: url('');">
                				<a href="http://www.greenparty.org.tw/news/20140905/177"  target="_blank" class="mosaic-overlay link" title="<?php echo $news_all[0]['node']['title']; ?>"></a><div class="mosaic-backdrop">
                				<div class="corner-date">09/05</div><img style="margin-top: 0px;" src="<?php echo $news_all[0]['node']['photo']; ?>" alt="<?php echo $news_all[0]['node']['title']; ?>" /></div>
                			</div>
                			<p><a href="http://www.greenparty.org.tw/news/20140905/177" target="_blank" style="text-decoration: initial;"><?php echo $news_all[0]['node']['title']; ?></a></p>
			</div> 

			
			<!-- Start Column -->	
			<div class="fourth widget footer-signup">
				<h3>訂閱電子報</h3>
				<p>關注綠黨最新消息</p>
            <form id="subscribe-newsletter" target="_blank" style="margin-top:0;" action="http://www.greenparty.org.tw/civicrm/mailing/subscribe" method="post">                							
				<input type="email" placeholder="Email" name="email" id="email" value="" />
				<input type="hidden" id="mark_x_2" name="mark_x_2" value="1">
				<input type="submit" class="btn small-btn" name="" value="訂閱" />
			</form>
			</div>
				
			<!-- Start Column -->	
			<div class="fourth widget last footer-action">
				<h3>行動參與，挺好的！</h3>
				<ul>
					<li><a href="http://www.greenparty.org.tw/civicrm/contribute/transact?reset=1&id=4" target="_blank">捐款給綠黨</a></li>
					<li><a href="http://www.greenparty.org.tw/support/201409/179" target="_blank" >成為志工</a></li>
					<li><a href="http://www.greenparty.org.tw/civicrm/contribute/transact?reset=1&id=2" target="_blank" >加入黨員</a></li>					
					<li><a href="http://www.greenparty.org.tw/contactus" target="_blank" >合作提案</a></li>
				</ul>
			</div>
			
		</div>
	</div>
	<!-- End Widget Footer -->			
				
	
	
	
	<!-- /////////////////// --> 
	<!-- Start Footer -->
	 <footer class="outter-wrapper feature">
			<div class="wrapper">
			<div class="clearfix">
				<div class="foot right">
					<!-- Social Media icons -->
					<ul class="social-link">
						<li><a href="http://green.democracy.tw" target="_self">綠黨 2014 政治代理人</a></li>
						<li>｜</li>						
						<li><a href="https://www.facebook.com/taiwangreenparty" target="_blank"><em class="fa fa-facebook-square"></em> 綠黨粉絲團</a></li>
					</ul>
				</div>	
				<!-- Copyright Info -->				
				<div class="foot left">&copy; Copyright Green Party Taiwan 2014</div>
			</div>
			</div>
	 </footer> 	
	 <!-- End Footer -->
    
		
	<!-- /////////////////// --> 
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53f45fd44ed6a9b9"></script>