	<!-- /////////////////// --> 			
	<!-- Start Widget Footer -->
	<div class="outter-wrapper widget-footer main clearfix">
		<div class="wrapper clearfix">
			
			<!-- Start Column -->
			<div class="fourth widget">
				<h3>台灣綠黨</h3>
				<p>台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介台灣綠黨簡介</p>				
			</div>

			<!-- Start Column -->
			<div class="fourth widget footer-news">
				<h3>最新訊息</h3>
                			<div class="mosaic-block fade">
                				<a href="#" class="mosaic-overlay link" title="新聞標題"></a><div class="mosaic-backdrop">
                				<div class="corner-date">8/26</div><img src="/img/small_thumb3.jpg" alt="Mock" /></div>
                			</div>
                			<h3 class="title"><a href="#">新聞標題</a></h3>
			</div> 

			
			<!-- Start Column -->	
			<div class="fourth widget footer-signup">
				<h3>訂閱電子報</h3>
				<p>關注綠黨最新消息</p>
            <form id="subscribe-newsletter" style="margin-top:0;" action="#" method="post">                							
				<input type="email" placeholder="Email" name="email" id="email" value="" />
				<input type="submit" class="btn small-btn" name="" value="訂閱" />
			</form>
			</div>
				
			<!-- Start Column -->	
			<div class="fourth widget last footer-action">
				<h3>行動參與，挺好的！</h3>
				<ul>
					<li><a href="#">捐款給綠黨</a></li>
					<li><a href="#">成為志工</a></li>
					<li><a href="#">加入黨員</a></li>					
					<li><a href="#">合作提案</a></li>
				</ul>
			</div>
			
		</div>
	</div>
	<!-- End Widget Footer -->			
				
	
	
	
	<!-- /////////////////// --> 
	<!-- Start Footer -->
	 <footer class="outter-wrapper feature">
			<div class="wrapper">
			<div class="clearfix">
				<div class="foot right">
					<!-- Social Media icons -->
					<ul class="social-link">
						<li><a href="https://www.facebook.com/taiwangreenparty" target="_blank"><?php echo $user['title']?>選舉動態首頁</a></li>
						<li>｜</li>						
						<li><a href="https://www.facebook.com/taiwangreenparty" target="_blank"><em class="icon-facebook-sign"></em> 綠黨粉絲團</a></li>
					</ul>
				</div>	
				<!-- Copyright Info -->				
				<div class="foot left">&copy; Copyright Green Party Taiwan 2014</div>
			</div>
			</div>
	 </footer> 	
	 <!-- End Footer -->
    
		
	<!-- /////////////////// --> 
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53f45fd44ed6a9b9"></script>